name: "Monitoring Stack"
description: "Prometheus, Node Exporter, Loki, and Promtail stack for Home Assistant"
version: "0.1.0"
slug: "monitoring_stack"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  9090/tcp: 9090
  9100/tcp: 9100
  8086/tcp: 8086
  3100/tcp: 3100
webui: "http://[HOST]:[PORT:9090]"
startup: application
boot: auto