global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9101']

  - job_name: 'home_assistant'
    static_configs:
      - targets: ['homeassistant:8123']