name: "Prometheus & Promtail"
description: "Prometheus for metrics collection and Promtail for log collection"
version: "1.0.0"
slug: "prometheus-promtail"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  9090/tcp: 9090
  9100/tcp: 9100