name: "Promtail"
description: "Promtail addon for Home Assistant"
version: "3.0.1"
slug: "promtail"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
  - x86_64
startup: services
boot: auto
options:
  log_level: info
  client:
    url: http://loki:3100/loki/api/v1/push
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  client:
    url: str
ports:
  9080/tcp: 9080
